# Generated by Django 4.2 on 2023-04-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodact',
            new_name='Product',
        ),
    ]
