# Generated by Django 4.2 on 2023-04-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_remove_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='shopapp.product'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('active', 'Active')], default='closed'),
        ),
    ]
